from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any, Protocol

from pydantic import BaseModel, Field


class ToolCall(BaseModel):
    """Represents a tool call from the LLM."""

    id: str = Field(..., description="Unique ID of the tool call")
    name: str = Field(..., description="Name of the tool to call")
    arguments: dict[str, Any] = Field(..., description="Arguments for the tool")


class LLMResponse(BaseModel):
    """Standardized response from an LLM provider."""

    content: str = Field(..., description="Text content generated by the model")
    tool_calls: list[ToolCall] = Field(default_factory=list, description="Tool calls requested")
    usage: dict[str, int] = Field(default_factory=dict, description="Token usage statistics")


class StreamChunk(BaseModel):
    """A chunk of streamed response."""

    content: str = Field("", description="Delta text content")


class Provider(Protocol):
    """Protocol for LLM providers."""

    async def chat(
        self,
        messages: list[dict[str, Any]],
        tools: list[dict[str, Any]] | None = None,
        system: str | None = None,
    ) -> LLMResponse:
        """Send a chat request to the LLM."""
        ...

    def stream(
        self,
        messages: list[dict[str, Any]],
        tools: list[dict[str, Any]] | None = None,
        system: str | None = None,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a chat request from the LLM."""
        ...
